### ISSUE TITLE
Copy/paste error in appdata file

### ISSUE THREAD

**Issue by hadess** [flathub/one.flipperzero.qFlipper#6]
https://github.com/flathub/one.flipperzero.qFlipper/blob/master/one.flipperzero.qFlipper.metainfo.xml#L26 says:
> You probably only need to install this application if you are having problems
> with your laptop battery, or are trying to work out what programs are using
> significant amounts of power.

This seems to be copy/pasted from gnome-power-manager:
https://gitlab.gnome.org/GNOME/gnome-power-manager/-/blob/master/data/appdata/org.gnome.PowerStats.appdata.xml.in#L15

This paragraph can just be removed.

**Comment by kowalski7cc** [comment]
Thanks, I have no idea how it got there!
